// Code generated by "stringer -type=WorkMode -output=work_mode_string.go"; DO NOT EDIT.

package backup

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GENERATE-1]
	_ = x[UPLOAD-2]
}

const _WorkMode_name = "GENERATEUPLOAD"

var _WorkMode_index = [...]uint8{0, 8, 14}

func (i WorkMode) String() string {
	i -= 1
	if i < 0 || i >= WorkMode(len(_WorkMode_index)-1) {
		return "WorkMode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _WorkMode_name[_WorkMode_index[i]:_WorkMode_index[i+1]]
}
